/**
 * Demo Data Seeder
 *
 * Populates the database with ~10 records per main table to facilitate manual testing.
 *
 * Prerequisites:
 *  - Schema loaded: psql -U postgres -d medsync_db -f server/database.sql
 *  - Users/staff seeded: node server/seedUsers.js (needed for doctors/admin)
 *  - server/.env correctly configured for DB access
 *
 * Usage:
 *  node server/seedDemoData.js
 */

const pool = require('./config/db');

function randInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function pick(arr) {
  return arr[randInt(0, arr.length - 1)];
}

function uniqueSeq(prefix = '') {
  // Basic unique sequence using timestamp and random
  return `${prefix}${Date.now()}${Math.floor(Math.random() * 10000)}`;
}

function randomDateInBusinessHours(daysFromNow = 0) {
  const base = new Date();
  base.setDate(base.getDate() + daysFromNow);
  // set a random hour between 9 and 16 to stay inside [08:00, 18:00]
  base.setHours(9 + randInt(0, 7), randInt(0, 1) ? 0 : 30, 0, 0);
  return base;
}

async function ensureProviders(client, desired = 5) {
  const { rows } = await client.query('SELECT id, name FROM insurance_providers ORDER BY id');
  if (rows.length >= desired) return rows;
  const toAdd = desired - rows.length;
  const added = [];
  for (let i = 0; i < toAdd; i++) {
    const name = `Demo Health ${i + 1}`;
    const res = await client.query(
      `INSERT INTO insurance_providers(name, contact_info, is_active)
       VALUES ($1, $2, true) RETURNING id, name`,
      [name, { phone: `+9411${randInt(1000000, 9999999)}`, email: `claims+${i}@demohealth.lk` }]
    );
    added.push(res.rows[0]);
  }
  return rows.concat(added);
}

async function ensureTreatments(client, desired = 10) {
  const existing = await client.query('SELECT id, name, price, category_id FROM treatments ORDER BY id');
  if (existing.rows.length >= desired) return existing.rows;
  // Ensure categories exist
  const cats = await client.query('SELECT id, name FROM treatment_categories ORDER BY id');
  if (cats.rows.length === 0) {
    throw new Error('No treatment categories found. Load schema first.');
  }
  const toAdd = desired - existing.rows.length;
  const added = [];
  for (let i = 0; i < toAdd; i++) {
    const name = `Demo Treatment ${i + 1}`;
    const price = randInt(1000, 8000);
    const cat = pick(cats.rows);
    const res = await client.query(
      `INSERT INTO treatments(name, description, price, category_id, is_active)
       VALUES ($1, $2, $3, $4, true) RETURNING id, name, price, category_id`,
      [name, 'Autogenerated demo treatment', price, cat.id]
    );
    added.push(res.rows[0]);
  }
  return existing.rows.concat(added);
}

async function ensureAdminUser(client) {
  const { rows } = await client.query("SELECT id FROM users WHERE role = 'admin' ORDER BY id LIMIT 1");
  if (!rows.length) throw new Error('No admin user found. Run: node server/seedUsers.js');
  return rows[0].id;
}

async function getActiveDoctors(client) {
  const { rows } = await client.query(
    `SELECT id, branch_id FROM medical_staff WHERE is_active = true ORDER BY id LIMIT 20`
  );
  if (!rows.length) throw new Error('No medical staff found. Run: node server/seedUsers.js');
  return rows;
}

async function getBranches(client) {
  const { rows } = await client.query('SELECT id FROM branches ORDER BY id');
  if (!rows.length) throw new Error('No branches found. Load schema with server/database.sql');
  return rows.map(r => r.id);
}

async function createPatients(client, count = 10, branchIds = []) {
  const firstNames = ['Nimal', 'Saman', 'Kasun', 'Amila', 'Ishara', 'Ruwan', 'Thilini', 'Chamari', 'Priyanka', 'Sanduni', 'Arjun', 'Kavindu'];
  const lastNames = ['Fernando', 'Perera', 'Silva', 'Jayawardena', 'Mendis', 'Gamage', 'Dias', 'Rajapaksha', 'Weerasinghe', 'De Silva'];
  const cities = ['Colombo', 'Kandy', 'Galle', 'Matara', 'Negombo', 'Gampaha'];

  const patients = [];
  for (let i = 0; i < count; i++) {
    // Address
    const addrRes = await client.query(
      `INSERT INTO addresses(line1, line2, city, state, postal_code)
       VALUES ($1, $2, $3, $4, $5) RETURNING id`,
      [
        `${randInt(10, 999)} Test Street`,
        Math.random() < 0.5 ? null : `Apt ${randInt(1, 20)}`,
        pick(cities),
        'Western Province',
        `${randInt(10000, 99999)}`
      ]
    );
    const addressId = addrRes.rows[0].id;

    const first = pick(firstNames);
    const last = pick(lastNames);
    const dobYear = randInt(1965, 2005);
    const dobMonth = randInt(1, 12);
    const dobDay = randInt(1, 28);
    const phone = `07${randInt(1, 9)}${randInt(1000000, 9999999)}`.slice(0, 10);
    const branch = pick(branchIds);

    const patRes = await client.query(
      `INSERT INTO patients(first_name, last_name, date_of_birth, gender, address_id, phone, email, registered_branch, is_active,
        Emergency_contact_name, Emergency_contact_phone, Emergency_contact_relation)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, true, $9, $10, $11)
       RETURNING id`,
      [
        first,
        last,
        `${dobYear}-${String(dobMonth).padStart(2, '0')}-${String(dobDay).padStart(2, '0')}`,
        Math.random() < 0.5 ? 'Male' : 'Female',
        addressId,
        phone,
        `${first.toLowerCase()}.${last.toLowerCase()}+${uniqueSeq('p')}@example.lk`,
        branch,
        'Emergency Contact',
        `07${randInt(1, 9)}${randInt(1000000, 9999999)}`.slice(0, 10),
        'Spouse'
      ]
    );
    const patientId = patRes.rows[0].id;

    // Also add a separate patient_contacts row
    await client.query(
      `INSERT INTO patient_contacts(patient_id, name, phone, relation)
       VALUES ($1, $2, $3, $4)`,
      [patientId, 'Emergency Contact', `07${randInt(1, 9)}${randInt(1000000, 9999999)}`.slice(0, 10), 'Sibling']
    );

    patients.push({ id: patientId, branchId: branch });
  }
  return patients;
}

async function createInsuranceForPatients(client, patients, providers) {
  const insured = [];
  for (const p of patients) {
    if (Math.random() < 0.7) { // 70% of patients have insurance
      const provider = pick(providers);
      // coverage_details JSON
      const coverage = {
        coverage_percentage: randInt(50, 90),
        max_claim: randInt(10000, 50000)
      };
      const exp = new Date();
      // Expire between -20 and +180 days from today to trigger notifications
      exp.setDate(exp.getDate() + randInt(-20, 180));
      const res = await client.query(
        `INSERT INTO patient_insurance(patient_id, provider_id, policy_number, coverage_details, expiration_date, is_active)
         VALUES ($1, $2, $3, $4, $5, true) RETURNING id`,
        [p.id, provider.id, `POL-${uniqueSeq('')}`, coverage, `${exp.getFullYear()}-${String(exp.getMonth()+1).padStart(2, '0')}-${String(exp.getDate()).padStart(2, '0')}`]
      );
      insured.push({ patientId: p.id, policyId: res.rows[0].id, providerId: provider.id });
    }
  }
  return insured;
}

async function createAppointments(client, patients, doctors) {
  const statuses = ['Scheduled', 'Confirmed', 'In Progress', 'Completed', 'Cancelled', 'No Show'];
  const types = ['Regular', 'Emergency', 'Walk-in', 'Follow-up'];
  const apps = [];
  for (let i = 0; i < patients.length; i++) {
    const patient = patients[i];
    const doc = pick(doctors);
    const daysOffset = randInt(-20, 20);
    const dt = randomDateInBusinessHours(daysOffset);
    const status = pick(statuses);
    const type = pick(types);
    const res = await client.query(
      `INSERT INTO appointments(patient_id, doctor_id, branch_id, appointment_datetime, status, type, notes)
       VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, appointment_datetime`,
      [patient.id, doc.id, doc.branch_id, dt.toISOString(), status, type, 'Demo appointment']
    );
    apps.push({ id: res.rows[0].id, patientId: patient.id, doctorId: doc.id, branchId: doc.branch_id, datetime: res.rows[0].appointment_datetime });
  }
  return apps;
}

async function createTreatmentRecords(client, appointments, treatments) {
  const byAppointment = new Map();
  for (const appt of appointments) {
    const recordsForAppt = [];
    const items = randInt(1, 2);
    const chosen = new Set();
    for (let i = 0; i < items; i++) {
      let t;
      // Avoid duplicates in same appointment
      do { t = pick(treatments); } while (chosen.has(t.id));
      chosen.add(t.id);
      const quantity = 1;
      const unitPrice = Number(t.price);
      const res = await client.query(
        `INSERT INTO treatment_records(appointment_id, treatment_id, quantity, unit_price, consultation_notes, recorded_by)
         VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, total_price` ,
        [appt.id, t.id, quantity, unitPrice, 'Routine procedure', appt.doctorId]
      );
      recordsForAppt.push(res.rows[0]);
    }
    byAppointment.set(appt.id, recordsForAppt);
  }
  return byAppointment;
}

async function createInvoices(client, appointments, recordsByAppt) {
  const invoices = [];
  for (const appt of appointments) {
    const recs = recordsByAppt.get(appt.id) || [];
    const total = recs.reduce((s, r) => s + Number(r.total_price), 0);
    const status = Math.random() < 0.4 ? 'Paid' : 'Sent';
    const res = await client.query(
      `INSERT INTO invoices(patient_id, appointment_id, invoice_number, total_amount, status)
       VALUES ($1, $2, $3, $4, $5) RETURNING id, status, total_amount`,
      [appt.patientId, appt.id, `INV-${uniqueSeq('')}`, total, status]
    );
    invoices.push({ id: res.rows[0].id, total: Number(res.rows[0].total_amount), status: res.rows[0].status, patientId: appt.patientId });
  }
  return invoices;
}

async function createPaymentsOrClaims(client, invoices, insuredMap, adminUserId) {
  // For half the invoices, create cash payments to full amount if marked Paid
  // For the other half (if patient has insurance), create an insurance claim (Approved or Paid)
  for (let i = 0; i < invoices.length; i++) {
    const inv = invoices[i];
    const useInsurance = i % 2 === 1 && insuredMap.has(inv.patientId);
    if (useInsurance) {
      const insuranceInfo = insuredMap.get(inv.patientId);
      // Claim amount up to invoice total
      const claimAmount = Math.min(inv.total, randInt(Math.floor(inv.total * 0.5), inv.total));
      const statuses = ['Submitted', 'Approved', 'Paid'];
      const status = pick(statuses);
      const approvedAmount = status === 'Submitted' ? 0 : Math.floor(claimAmount * randInt(50, 90) / 100);
      await client.query(
        `INSERT INTO insurance_claims(invoice_id, patient_insurance_id, claim_number, claim_amount, approved_amount, status)
         VALUES ($1, $2, $3, $4, $5, $6)`,
        [inv.id, insuranceInfo.policyId, `CLM-${uniqueSeq('')}`, claimAmount, approvedAmount, status]
      );
      // Triggers may create payments if status transitions to Paid and approved amount > 0
    } else if (inv.status === 'Paid') {
      // Create cash payment for the full total
      await client.query(
        `INSERT INTO payments(invoice_id, amount, payment_method, processed_by, notes)
         VALUES ($1, $2, 'Cash', $3, $4)`,
        [inv.id, inv.total, adminUserId, 'Demo payment']
      );
    } else if (Math.random() < 0.3) {
      // Partial payment for Sent invoice
      const partial = Math.max(500, Math.min(inv.total - 500, Math.floor(inv.total * 0.5)));
      if (partial > 0) {
        await client.query(
          `INSERT INTO payments(invoice_id, amount, payment_method, processed_by, notes)
           VALUES ($1, $2, 'Cash', $3, $4)`,
          [inv.id, partial, adminUserId, 'Demo partial payment']
        );
      }
    }
  }
}

async function main() {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    const adminUserId = await ensureAdminUser(client);
    const branches = await getBranches(client);
    const doctors = await getActiveDoctors(client);
    const providers = await ensureProviders(client, 5);
    const treatments = await ensureTreatments(client, 10);

    const patients = await createPatients(client, 10, branches);
    const insured = await createInsuranceForPatients(client, patients, providers);
    const insuredMap = new Map(insured.map(i => [i.patientId, i]));

    const appointments = await createAppointments(client, patients, doctors);
    const recordsByAppt = await createTreatmentRecords(client, appointments, treatments);
    const invoices = await createInvoices(client, appointments, recordsByAppt);

    await createPaymentsOrClaims(client, invoices, insuredMap, adminUserId);

    await client.query('COMMIT');
    console.log('✓ Demo data seeding complete.');
  } catch (err) {
    await client.query('ROLLBACK');
    console.error('✗ Error seeding demo data:', err.message);
    process.exitCode = 1;
  } finally {
    client.release();
    // Allow background pool to finish logging
    setTimeout(() => process.exit(process.exitCode || 0), 50);
  }
}

main();

